# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wirock_extended.ui'
#
# Created: Tue Oct 29 17:41:15 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName(_fromUtf8("dialog"))
        dialog.resize(240, 224)
        self.gridLayout = QtGui.QGridLayout(dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.devaddrEdit = QtGui.QLineEdit(dialog)
        self.devaddrEdit.setObjectName(_fromUtf8("devaddrEdit"))
        self.gridLayout.addWidget(self.devaddrEdit, 1, 1, 1, 1)
        self.label = QtGui.QLabel(dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.checkBox_5 = QtGui.QCheckBox(dialog)
        self.checkBox_5.setText(_fromUtf8(""))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout_4.addWidget(self.checkBox_5, 0, 4, 1, 1)
        self.checkBox_1 = QtGui.QCheckBox(dialog)
        self.checkBox_1.setText(_fromUtf8(""))
        self.checkBox_1.setObjectName(_fromUtf8("checkBox_1"))
        self.gridLayout_4.addWidget(self.checkBox_1, 0, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(dialog)
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_4.addWidget(self.checkBox_2, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 5, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(dialog)
        self.checkBox_4.setText(_fromUtf8(""))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_4.addWidget(self.checkBox_4, 0, 3, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(dialog)
        self.checkBox_3.setText(_fromUtf8(""))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_4.addWidget(self.checkBox_3, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(dialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(dialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 1, 2, 1, 1)
        self.label_11 = QtGui.QLabel(dialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 1, 3, 1, 1)
        self.label_12 = QtGui.QLabel(dialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 1, 4, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 5, 0, 1, 1)
        self.label_2 = QtGui.QLabel(dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 4, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.comboBox = QtGui.QComboBox(dialog)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.onButton = QtGui.QPushButton(dialog)
        self.onButton.setObjectName(_fromUtf8("onButton"))
        self.horizontalLayout_2.addWidget(self.onButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_2, 8, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.offButton = QtGui.QPushButton(dialog)
        self.offButton.setObjectName(_fromUtf8("offButton"))
        self.horizontalLayout_4.addWidget(self.offButton)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_4, 8, 1, 1, 1)
        self.label_3 = QtGui.QLabel(dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.gainSlider = QtGui.QSlider(dialog)
        self.gainSlider.setMaximum(45)
        self.gainSlider.setPageStep(5)
        self.gainSlider.setSliderPosition(15)
        self.gainSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gainSlider.setObjectName(_fromUtf8("gainSlider"))
        self.gridLayout.addWidget(self.gainSlider, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.line = QtGui.QFrame(dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 7, 0, 1, 2)
        self.line_2 = QtGui.QFrame(dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 2)
        self.devtypeBox = QtGui.QComboBox(dialog)
        self.devtypeBox.setObjectName(_fromUtf8("devtypeBox"))
        self.devtypeBox.addItem(_fromUtf8(""))
        self.devtypeBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.devtypeBox, 0, 1, 1, 1)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        dialog.setWindowTitle(_translate("dialog", "gr-wirock", None))
        self.label_4.setText(_translate("dialog", "Device Address:", None))
        self.devaddrEdit.setPlaceholderText(_translate("dialog", "empty = 1st", None))
        self.label.setText(_translate("dialog", "DIP Position:", None))
        self.label_8.setText(_translate("dialog", "1", None))
        self.label_9.setText(_translate("dialog", "2", None))
        self.label_10.setText(_translate("dialog", "3", None))
        self.label_11.setText(_translate("dialog", "4", None))
        self.label_12.setText(_translate("dialog", "5", None))
        self.label_2.setText(_translate("dialog", "Unit to switch:", None))
        self.comboBox.setItemText(0, _translate("dialog", "A", None))
        self.comboBox.setItemText(1, _translate("dialog", "B", None))
        self.comboBox.setItemText(2, _translate("dialog", "C", None))
        self.comboBox.setItemText(3, _translate("dialog", "D", None))
        self.comboBox.setItemText(4, _translate("dialog", "E", None))
        self.onButton.setText(_translate("dialog", "Turn ON", None))
        self.offButton.setText(_translate("dialog", "Turn OFF", None))
        self.label_3.setText(_translate("dialog", "Device Type:", None))
        self.label_5.setText(_translate("dialog", "Gain:", None))
        self.devtypeBox.setItemText(0, _translate("dialog", "UHD", None))
        self.devtypeBox.setItemText(1, _translate("dialog", "HackRF", None))

